# Default values for chartSample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: ${ENVIRONMENT}

sample:
  replicaCount: ${SAMPLE_REPLICAS}
  image:
    repo: ${IMG_SAMPLE_HELM_SOURCENAME}
    tag: ${IMG_SAMPLE_HELM_VERSIONNAME}
  resources:
    limits:
      cpu: ${SAMPLE_CPU}
      memory: ${SAMPLE_MEMORY}
  port: ${SAMPLE_PORT}

nginx:
  image:
    repo: ${IMG_NGINX_HELM_SOURCENAME}
    tag: ${IMG_NGINX_HELM_VERSIONNAME}

